const NASHOR_BLACK_100 = "#1e2025";
const NASHOR_GRAY = "#2f3037";
const NASHOR_BLUE_PRIMARY = "#3a38ab";
const NASHOR_WHITE = "#fafafa";
const NASHOR_TURQ_LINKS = "#3595a1";
const NASHOR_RED_ERROR = "#981414";

export {
  NASHOR_BLACK_100,
  NASHOR_BLUE_PRIMARY,
  NASHOR_GRAY,
  NASHOR_RED_ERROR,
  NASHOR_TURQ_LINKS,
  NASHOR_WHITE,
};
